### ISSUE TITLE
Mandatory fields are not highlighted

### ISSUE THREAD

**Issue by chetanls** [uidev547/corridorApp#67]
Certain fields are mandatory (ex: Estimated Hours). There is no indicator as such and when I try to save in the final screen, the error message says the mandatory fields need to be filled up in the 'other tabs'. One has to scan thru the various tabs to find out where he/she has missed entering the details,

**Comment by uidev547** [comment]
now created same issue at  https://gitlab.pramati.com/cev3/letsbuild/issues/43
